# Generated by Django 3.1.4 on 2021-01-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Coupon',
        ),
    ]
